### REALIZAR LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "LOGIN": "13894878000160",
  "SENHA": "XPTO"
}

# ----------------------------------------------------------

### BUSCAR TODOS OS PEDIDOS
POST http://localhost:3000/api/order
Content-Type: application/json

{
  "CLIENTE": "003364",
  "DATAINI": "20240701",
  "DATAFIM": "20250731",
  "FILIAL": "01",
  "LOJA": "01"
}

# ----------------------------------------------------------


### BUSCAR TODOS OS ITENS
POST http://localhost:3000/api/itens-pedido?cliente=003364&filial=0101&loja=01

# ----------------------------------------------------------