### REALIZAR LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "LOGIN": "13894878000160",
  "SENHA": "12345"
}

# ----------------------------------------------------------

### BUSCAR TODOS OS PEDIDOS
POST http://localhost:3000/api/order
Content-Type: application/json

{
  "CLIENTE": "003364",
  "DATAINI": "20200101",
  "DATAFIM": "20250731",
  "FILIAL": "01",
  "LOJA": "01"
}

# ----------------------------------------------------------

### BUSCAR TODOS OS ITENS DE UM CLIENTE
POST http://localhost:3000/api/itens-pedido?cliente=003364&filial=0101&loja=01

# ----------------------------------------------------------

### BUSCAR TODOS OS PEDIDOS E SEUS ITENS
POST http://localhost:3000/api/pedidos-itens
Content-Type: application/json

{
  "CLIENTE": "003364",
  "DATAINI": "20200101",
  "DATAFIM": "20250731",
  "FILIAL": "0101",
  "LOJA": "01",
  "NUMERO_PEDIDO": "072094"
}

