import type { Metadata } from "next";
import { Kodchasan, Orbitron } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/auth-context";

const kodchasan = Kodchasan({
  variable: '--font-kodchasan',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

const orbitron = Orbitron({
  variable: '--font-orbitron',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kodchasan.variable} ${orbitron.variable} antialiased`}
      >
        <AuthProvider>

        {children}
        </AuthProvider>

      </body>
    </html>
  );
}
